//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapIntegration.BrukerInfo {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
    public partial class feil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string feilgruppekodeField;
        
        private string feilgruppetekstField;
        
        private string feilkodeField;
        
        private string feiltekstField;
        
        private string feilmeldingField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string feilgruppekode {
            get {
                return this.feilgruppekodeField;
            }
            set {
                this.feilgruppekodeField = value;
                this.RaisePropertyChanged("feilgruppekode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string feilgruppetekst {
            get {
                return this.feilgruppetekstField;
            }
            set {
                this.feilgruppetekstField = value;
                this.RaisePropertyChanged("feilgruppetekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string feilkode {
            get {
                return this.feilkodeField;
            }
            set {
                this.feilkodeField = value;
                this.RaisePropertyChanged("feilkode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string feiltekst {
            get {
                return this.feiltekstField;
            }
            set {
                this.feiltekstField = value;
                this.RaisePropertyChanged("feiltekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string feilmelding {
            get {
                return this.feilmeldingField;
            }
            set {
                this.feilmeldingField = value;
                this.RaisePropertyChanged("feilmelding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class bruker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brukernavnField;
        
        private kontaktinfo kontaktinfoField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string brukernavn {
            get {
                return this.brukernavnField;
            }
            set {
                this.brukernavnField = value;
                this.RaisePropertyChanged("brukernavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public kontaktinfo kontaktinfo {
            get {
                return this.kontaktinfoField;
            }
            set {
                this.kontaktinfoField = value;
                this.RaisePropertyChanged("kontaktinfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class kontaktinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string navnField;
        
        private adresse postadresseField;
        
        private string tlfnrField;
        
        private string telefaksField;
        
        private string epostField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public adresse postadresse {
            get {
                return this.postadresseField;
            }
            set {
                this.postadresseField = value;
                this.RaisePropertyChanged("postadresse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tlfnr {
            get {
                return this.tlfnrField;
            }
            set {
                this.tlfnrField = value;
                this.RaisePropertyChanged("tlfnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string telefaks {
            get {
                return this.telefaksField;
            }
            set {
                this.telefaksField = value;
                this.RaisePropertyChanged("telefaks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
                this.RaisePropertyChanged("epost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class adresse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adresse1Field;
        
        private string postnrField;
        
        private string poststedField;
        
        private string landField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adresse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adresse1 {
            get {
                return this.adresse1Field;
            }
            set {
                this.adresse1Field = value;
                this.RaisePropertyChanged("adresse1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
                this.RaisePropertyChanged("postnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
                this.RaisePropertyChanged("poststed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
                this.RaisePropertyChanged("land");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class kunde : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orgnrField;
        
        private kontaktinfo kontaktinfoField;
        
        private kontaktinfo kontaktpersonField;
        
        private kontaktinfo gjenpartsinfoField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orgnr {
            get {
                return this.orgnrField;
            }
            set {
                this.orgnrField = value;
                this.RaisePropertyChanged("orgnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public kontaktinfo kontaktinfo {
            get {
                return this.kontaktinfoField;
            }
            set {
                this.kontaktinfoField = value;
                this.RaisePropertyChanged("kontaktinfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public kontaktinfo kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
                this.RaisePropertyChanged("kontaktperson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public kontaktinfo gjenpartsinfo {
            get {
                return this.gjenpartsinfoField;
            }
            set {
                this.gjenpartsinfoField = value;
                this.RaisePropertyChanged("gjenpartsinfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.wsdl", ConfigurationName="BrukerInfo.brukerinfoPortType")]
    public interface brukerinfoPortType {
        
        // CODEGEN: Generating message contract since the operation hentBrukerinfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.BrukerInfo.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.BrukerInfo.hentBrukerinfoResponse hentBrukerinfo(SoapIntegration.BrukerInfo.hentBrukerinfoRequest request);
        
        // CODEGEN: Generating message contract since the operation sendIPhoneFeil is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.BrukerInfo.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.BrukerInfo.sendIPhoneFeilResponse sendIPhoneFeil(SoapIntegration.BrukerInfo.sendIPhoneFeilRequest request);
        
        // CODEGEN: Generating message contract since the operation settBrukerinfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.BrukerInfo.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.BrukerInfo.settBrukerinfoResponse settBrukerinfo(SoapIntegration.BrukerInfo.settBrukerinfoRequest request);
        
        // CODEGEN: Generating message contract since the operation hentDebiteringsgrunnlag is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.BrukerInfo.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.BrukerInfo.hentDebiteringsgrunnlagResponse hentDebiteringsgrunnlag(SoapIntegration.BrukerInfo.hentDebiteringsgrunnlagRequest request);
        
        // CODEGEN: Generating message contract since the operation hentPrisliste is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.BrukerInfo.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.BrukerInfo.hentPrislisteResponse hentPrisliste(SoapIntegration.BrukerInfo.hentPrislisteRequest request);
        
        // CODEGEN: Generating message contract since the operation hentNyttPassord is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.BrukerInfo.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.BrukerInfo.hentNyttPassordResponse hentNyttPassord(SoapIntegration.BrukerInfo.hentNyttPassordRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class Brukersesjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private distribusjonskanal distribusjonskanalField;
        
        private string systemnavnField;
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string delegertBrukernavnField;
        
        private string sesjonsidField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public distribusjonskanal distribusjonskanal {
            get {
                return this.distribusjonskanalField;
            }
            set {
                this.distribusjonskanalField = value;
                this.RaisePropertyChanged("distribusjonskanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string systemnavn {
            get {
                return this.systemnavnField;
            }
            set {
                this.systemnavnField = value;
                this.RaisePropertyChanged("systemnavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brukernavn", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("passord", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string delegertBrukernavn {
            get {
                return this.delegertBrukernavnField;
            }
            set {
                this.delegertBrukernavnField = value;
                this.RaisePropertyChanged("delegertBrukernavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sesjonsid {
            get {
                return this.sesjonsidField;
            }
            set {
                this.sesjonsidField = value;
                this.RaisePropertyChanged("sesjonsid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public enum distribusjonskanal {
        
        /// <remarks/>
        PTP,
        
        /// <remarks/>
        GUI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":brukernavn")]
        brukernavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":passord")]
        passord,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class hentBrukerinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class Transaksjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referanseField;
        
        private bool visDetaljerField;
        
        private bool visDetaljerFieldSpecified;
        
        private bool visResponstidField;
        
        private bool visResponstidFieldSpecified;
        
        private bool visRaadataField;
        
        private bool visRaadataFieldSpecified;
        
        private string saksreferanseField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string referanse {
            get {
                return this.referanseField;
            }
            set {
                this.referanseField = value;
                this.RaisePropertyChanged("referanse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool visDetaljer {
            get {
                return this.visDetaljerField;
            }
            set {
                this.visDetaljerField = value;
                this.RaisePropertyChanged("visDetaljer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visDetaljerSpecified {
            get {
                return this.visDetaljerFieldSpecified;
            }
            set {
                this.visDetaljerFieldSpecified = value;
                this.RaisePropertyChanged("visDetaljerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool visResponstid {
            get {
                return this.visResponstidField;
            }
            set {
                this.visResponstidField = value;
                this.RaisePropertyChanged("visResponstid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visResponstidSpecified {
            get {
                return this.visResponstidFieldSpecified;
            }
            set {
                this.visResponstidFieldSpecified = value;
                this.RaisePropertyChanged("visResponstidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool visRaadata {
            get {
                return this.visRaadataField;
            }
            set {
                this.visRaadataField = value;
                this.RaisePropertyChanged("visRaadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visRaadataSpecified {
            get {
                return this.visRaadataFieldSpecified;
            }
            set {
                this.visRaadataFieldSpecified = value;
                this.RaisePropertyChanged("visRaadataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string saksreferanse {
            get {
                return this.saksreferanseField;
            }
            set {
                this.saksreferanseField = value;
                this.RaisePropertyChanged("saksreferanse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class Brukerinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kunde kundeField;
        
        private bruker brukerField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kunde kunde {
            get {
                return this.kundeField;
            }
            set {
                this.kundeField = value;
                this.RaisePropertyChanged("kunde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bruker bruker {
            get {
                return this.brukerField;
            }
            set {
                this.brukerField = value;
                this.RaisePropertyChanged("bruker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentBrukerinfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.hentBrukerinfo hentBrukerinfo;
        
        public hentBrukerinfoRequest() {
        }
        
        public hentBrukerinfoRequest(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentBrukerinfo hentBrukerinfo) {
            this.Brukersesjon = Brukersesjon;
            this.hentBrukerinfo = hentBrukerinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentBrukerinfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.BrukerInfo.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.Brukerinfo Brukerinfo;
        
        public hentBrukerinfoResponse() {
        }
        
        public hentBrukerinfoResponse(SoapIntegration.BrukerInfo.Transaksjon Transaksjon, SoapIntegration.BrukerInfo.Brukerinfo Brukerinfo) {
            this.Transaksjon = Transaksjon;
            this.Brukerinfo = Brukerinfo;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class sendIPhoneFeil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brukernavnField;
        
        private string feiltypeField;
        
        private string feilmeldingField;
        
        private string klassenavnField;
        
        private string metodenavnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string brukernavn {
            get {
                return this.brukernavnField;
            }
            set {
                this.brukernavnField = value;
                this.RaisePropertyChanged("brukernavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string feiltype {
            get {
                return this.feiltypeField;
            }
            set {
                this.feiltypeField = value;
                this.RaisePropertyChanged("feiltype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string feilmelding {
            get {
                return this.feilmeldingField;
            }
            set {
                this.feilmeldingField = value;
                this.RaisePropertyChanged("feilmelding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string klassenavn {
            get {
                return this.klassenavnField;
            }
            set {
                this.klassenavnField = value;
                this.RaisePropertyChanged("klassenavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string metodenavn {
            get {
                return this.metodenavnField;
            }
            set {
                this.metodenavnField = value;
                this.RaisePropertyChanged("metodenavn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class OK : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendIPhoneFeilRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.sendIPhoneFeil sendIPhoneFeil;
        
        public sendIPhoneFeilRequest() {
        }
        
        public sendIPhoneFeilRequest(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.sendIPhoneFeil sendIPhoneFeil) {
            this.Brukersesjon = Brukersesjon;
            this.sendIPhoneFeil = sendIPhoneFeil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendIPhoneFeilResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.BrukerInfo.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.OK OK;
        
        public sendIPhoneFeilResponse() {
        }
        
        public sendIPhoneFeilResponse(SoapIntegration.BrukerInfo.Transaksjon Transaksjon, SoapIntegration.BrukerInfo.OK OK) {
            this.Transaksjon = Transaksjon;
            this.OK = OK;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class settBrukerinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kontaktinfo kontaktinfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kontaktinfo kontaktinfo {
            get {
                return this.kontaktinfoField;
            }
            set {
                this.kontaktinfoField = value;
                this.RaisePropertyChanged("kontaktinfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class settBrukerinfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.settBrukerinfo settBrukerinfo;
        
        public settBrukerinfoRequest() {
        }
        
        public settBrukerinfoRequest(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.settBrukerinfo settBrukerinfo) {
            this.Brukersesjon = Brukersesjon;
            this.settBrukerinfo = settBrukerinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class settBrukerinfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.BrukerInfo.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.OK OK;
        
        public settBrukerinfoResponse() {
        }
        
        public settBrukerinfoResponse(SoapIntegration.BrukerInfo.Transaksjon Transaksjon, SoapIntegration.BrukerInfo.OK OK) {
            this.Transaksjon = Transaksjon;
            this.OK = OK;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class hentDebiteringsgrunnlag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fraField;
        
        private bool fraFieldSpecified;
        
        private System.DateTime tilField;
        
        private bool tilFieldSpecified;
        
        private string tjenesteField;
        
        private string produktField;
        
        private string referanseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime fra {
            get {
                return this.fraField;
            }
            set {
                this.fraField = value;
                this.RaisePropertyChanged("fra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fraSpecified {
            get {
                return this.fraFieldSpecified;
            }
            set {
                this.fraFieldSpecified = value;
                this.RaisePropertyChanged("fraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime til {
            get {
                return this.tilField;
            }
            set {
                this.tilField = value;
                this.RaisePropertyChanged("til");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tilSpecified {
            get {
                return this.tilFieldSpecified;
            }
            set {
                this.tilFieldSpecified = value;
                this.RaisePropertyChanged("tilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tjeneste {
            get {
                return this.tjenesteField;
            }
            set {
                this.tjenesteField = value;
                this.RaisePropertyChanged("tjeneste");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string produkt {
            get {
                return this.produktField;
            }
            set {
                this.produktField = value;
                this.RaisePropertyChanged("produkt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referanse {
            get {
                return this.referanseField;
            }
            set {
                this.referanseField = value;
                this.RaisePropertyChanged("referanse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class Debiteringsgrunnlag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DebiteringsgrunnlagStatuskode statuskodeField;
        
        private string statustekstField;
        
        private string antallField;
        
        private DebiteringsgrunnlagDebitering[] debiteringerField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DebiteringsgrunnlagStatuskode statuskode {
            get {
                return this.statuskodeField;
            }
            set {
                this.statuskodeField = value;
                this.RaisePropertyChanged("statuskode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statustekst {
            get {
                return this.statustekstField;
            }
            set {
                this.statustekstField = value;
                this.RaisePropertyChanged("statustekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string antall {
            get {
                return this.antallField;
            }
            set {
                this.antallField = value;
                this.RaisePropertyChanged("antall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("debitering", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DebiteringsgrunnlagDebitering[] debiteringer {
            get {
                return this.debiteringerField;
            }
            set {
                this.debiteringerField = value;
                this.RaisePropertyChanged("debiteringer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public enum DebiteringsgrunnlagStatuskode {
        
        /// <remarks/>
        komplett,
        
        /// <remarks/>
        ingen,
        
        /// <remarks/>
        trunkert,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class DebiteringsgrunnlagDebitering : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime tidspunktField;
        
        private string tjenesteField;
        
        private string produktField;
        
        private string tjenestebeskrivelseField;
        
        private string produktbeskrivelseField;
        
        private string soekekodeField;
        
        private string soekeverdiField;
        
        private string referanseField;
        
        private string antallField;
        
        private System.Nullable<decimal> prisField;
        
        private System.Nullable<decimal> rabattField;
        
        private System.Nullable<decimal> mvaField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
                this.RaisePropertyChanged("tidspunkt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tjeneste {
            get {
                return this.tjenesteField;
            }
            set {
                this.tjenesteField = value;
                this.RaisePropertyChanged("tjeneste");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string produkt {
            get {
                return this.produktField;
            }
            set {
                this.produktField = value;
                this.RaisePropertyChanged("produkt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tjenestebeskrivelse {
            get {
                return this.tjenestebeskrivelseField;
            }
            set {
                this.tjenestebeskrivelseField = value;
                this.RaisePropertyChanged("tjenestebeskrivelse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string produktbeskrivelse {
            get {
                return this.produktbeskrivelseField;
            }
            set {
                this.produktbeskrivelseField = value;
                this.RaisePropertyChanged("produktbeskrivelse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string soekekode {
            get {
                return this.soekekodeField;
            }
            set {
                this.soekekodeField = value;
                this.RaisePropertyChanged("soekekode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string soekeverdi {
            get {
                return this.soekeverdiField;
            }
            set {
                this.soekeverdiField = value;
                this.RaisePropertyChanged("soekeverdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string referanse {
            get {
                return this.referanseField;
            }
            set {
                this.referanseField = value;
                this.RaisePropertyChanged("referanse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=8)]
        public string antall {
            get {
                return this.antallField;
            }
            set {
                this.antallField = value;
                this.RaisePropertyChanged("antall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<decimal> pris {
            get {
                return this.prisField;
            }
            set {
                this.prisField = value;
                this.RaisePropertyChanged("pris");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<decimal> rabatt {
            get {
                return this.rabattField;
            }
            set {
                this.rabattField = value;
                this.RaisePropertyChanged("rabatt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<decimal> mva {
            get {
                return this.mvaField;
            }
            set {
                this.mvaField = value;
                this.RaisePropertyChanged("mva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=12)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentDebiteringsgrunnlagRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.hentDebiteringsgrunnlag hentDebiteringsgrunnlag;
        
        public hentDebiteringsgrunnlagRequest() {
        }
        
        public hentDebiteringsgrunnlagRequest(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentDebiteringsgrunnlag hentDebiteringsgrunnlag) {
            this.Brukersesjon = Brukersesjon;
            this.hentDebiteringsgrunnlag = hentDebiteringsgrunnlag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentDebiteringsgrunnlagResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.BrukerInfo.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.Debiteringsgrunnlag Debiteringsgrunnlag;
        
        public hentDebiteringsgrunnlagResponse() {
        }
        
        public hentDebiteringsgrunnlagResponse(SoapIntegration.BrukerInfo.Transaksjon Transaksjon, SoapIntegration.BrukerInfo.Debiteringsgrunnlag Debiteringsgrunnlag) {
            this.Transaksjon = Transaksjon;
            this.Debiteringsgrunnlag = Debiteringsgrunnlag;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class hentPrisliste : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class Prisliste : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PrislisteTjeneste[] tjenesterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tjeneste", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PrislisteTjeneste[] tjenester {
            get {
                return this.tjenesterField;
            }
            set {
                this.tjenesterField = value;
                this.RaisePropertyChanged("tjenester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class PrislisteTjeneste : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string navnField;
        
        private string beskrivelseField;
        
        private PrislisteTjenesteProdukt[] produkterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
                this.RaisePropertyChanged("beskrivelse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("produkt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PrislisteTjenesteProdukt[] produkter {
            get {
                return this.produkterField;
            }
            set {
                this.produkterField = value;
                this.RaisePropertyChanged("produkter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class PrislisteTjenesteProdukt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string navnField;
        
        private string beskrivelseField;
        
        private System.Nullable<decimal> prisField;
        
        private System.Nullable<decimal> rabattField;
        
        private System.Nullable<decimal> mvaField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
                this.RaisePropertyChanged("beskrivelse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<decimal> pris {
            get {
                return this.prisField;
            }
            set {
                this.prisField = value;
                this.RaisePropertyChanged("pris");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<decimal> rabatt {
            get {
                return this.rabattField;
            }
            set {
                this.rabattField = value;
                this.RaisePropertyChanged("rabatt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<decimal> mva {
            get {
                return this.mvaField;
            }
            set {
                this.mvaField = value;
                this.RaisePropertyChanged("mva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentPrislisteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.hentPrisliste hentPrisliste;
        
        public hentPrislisteRequest() {
        }
        
        public hentPrislisteRequest(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentPrisliste hentPrisliste) {
            this.Brukersesjon = Brukersesjon;
            this.hentPrisliste = hentPrisliste;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentPrislisteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.BrukerInfo.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.Prisliste Prisliste;
        
        public hentPrislisteResponse() {
        }
        
        public hentPrislisteResponse(SoapIntegration.BrukerInfo.Transaksjon Transaksjon, SoapIntegration.BrukerInfo.Prisliste Prisliste) {
            this.Transaksjon = Transaksjon;
            this.Prisliste = Prisliste;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class hentNyttPassord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brukernavnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string brukernavn {
            get {
                return this.brukernavnField;
            }
            set {
                this.brukernavnField = value;
                this.RaisePropertyChanged("brukernavn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public partial class NyttPassord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NyttPassordStatuskode statuskodeField;
        
        private string statustekstField;
        
        private string epostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public NyttPassordStatuskode statuskode {
            get {
                return this.statuskodeField;
            }
            set {
                this.statuskodeField = value;
                this.RaisePropertyChanged("statuskode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statustekst {
            get {
                return this.statustekstField;
            }
            set {
                this.statustekstField = value;
                this.RaisePropertyChanged("statustekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
                this.RaisePropertyChanged("epost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd")]
    public enum NyttPassordStatuskode {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        uregistrert,
        
        /// <remarks/>
        sperret,
        
        /// <remarks/>
        epostfeil,
        
        /// <remarks/>
        fastpassord,
        
        /// <remarks/>
        endretpassord,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentNyttPassordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.hentNyttPassord hentNyttPassord;
        
        public hentNyttPassordRequest() {
        }
        
        public hentNyttPassordRequest(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentNyttPassord hentNyttPassord) {
            this.Brukersesjon = Brukersesjon;
            this.hentNyttPassord = hentNyttPassord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentNyttPassordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.BrukerInfo.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukerinfo/2006-07-07/Brukerinfo.xsd", Order=0)]
        public SoapIntegration.BrukerInfo.NyttPassord NyttPassord;
        
        public hentNyttPassordResponse() {
        }
        
        public hentNyttPassordResponse(SoapIntegration.BrukerInfo.Transaksjon Transaksjon, SoapIntegration.BrukerInfo.NyttPassord NyttPassord) {
            this.Transaksjon = Transaksjon;
            this.NyttPassord = NyttPassord;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface brukerinfoPortTypeChannel : SoapIntegration.BrukerInfo.brukerinfoPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class brukerinfoPortTypeClient : System.ServiceModel.ClientBase<SoapIntegration.BrukerInfo.brukerinfoPortType>, SoapIntegration.BrukerInfo.brukerinfoPortType {
        
        public brukerinfoPortTypeClient() {
        }
        
        public brukerinfoPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public brukerinfoPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public brukerinfoPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public brukerinfoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.BrukerInfo.hentBrukerinfoResponse SoapIntegration.BrukerInfo.brukerinfoPortType.hentBrukerinfo(SoapIntegration.BrukerInfo.hentBrukerinfoRequest request) {
            return base.Channel.hentBrukerinfo(request);
        }
        
        public SoapIntegration.BrukerInfo.Transaksjon hentBrukerinfo(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentBrukerinfo hentBrukerinfo1, out SoapIntegration.BrukerInfo.Brukerinfo Brukerinfo) {
            SoapIntegration.BrukerInfo.hentBrukerinfoRequest inValue = new SoapIntegration.BrukerInfo.hentBrukerinfoRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.hentBrukerinfo = hentBrukerinfo1;
            SoapIntegration.BrukerInfo.hentBrukerinfoResponse retVal = ((SoapIntegration.BrukerInfo.brukerinfoPortType)(this)).hentBrukerinfo(inValue);
            Brukerinfo = retVal.Brukerinfo;
            return retVal.Transaksjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.BrukerInfo.sendIPhoneFeilResponse SoapIntegration.BrukerInfo.brukerinfoPortType.sendIPhoneFeil(SoapIntegration.BrukerInfo.sendIPhoneFeilRequest request) {
            return base.Channel.sendIPhoneFeil(request);
        }
        
        public SoapIntegration.BrukerInfo.Transaksjon sendIPhoneFeil(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.sendIPhoneFeil sendIPhoneFeil1, out SoapIntegration.BrukerInfo.OK OK) {
            SoapIntegration.BrukerInfo.sendIPhoneFeilRequest inValue = new SoapIntegration.BrukerInfo.sendIPhoneFeilRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.sendIPhoneFeil = sendIPhoneFeil1;
            SoapIntegration.BrukerInfo.sendIPhoneFeilResponse retVal = ((SoapIntegration.BrukerInfo.brukerinfoPortType)(this)).sendIPhoneFeil(inValue);
            OK = retVal.OK;
            return retVal.Transaksjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.BrukerInfo.settBrukerinfoResponse SoapIntegration.BrukerInfo.brukerinfoPortType.settBrukerinfo(SoapIntegration.BrukerInfo.settBrukerinfoRequest request) {
            return base.Channel.settBrukerinfo(request);
        }
        
        public SoapIntegration.BrukerInfo.Transaksjon settBrukerinfo(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.settBrukerinfo settBrukerinfo1, out SoapIntegration.BrukerInfo.OK OK) {
            SoapIntegration.BrukerInfo.settBrukerinfoRequest inValue = new SoapIntegration.BrukerInfo.settBrukerinfoRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.settBrukerinfo = settBrukerinfo1;
            SoapIntegration.BrukerInfo.settBrukerinfoResponse retVal = ((SoapIntegration.BrukerInfo.brukerinfoPortType)(this)).settBrukerinfo(inValue);
            OK = retVal.OK;
            return retVal.Transaksjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.BrukerInfo.hentDebiteringsgrunnlagResponse SoapIntegration.BrukerInfo.brukerinfoPortType.hentDebiteringsgrunnlag(SoapIntegration.BrukerInfo.hentDebiteringsgrunnlagRequest request) {
            return base.Channel.hentDebiteringsgrunnlag(request);
        }
        
        public SoapIntegration.BrukerInfo.Transaksjon hentDebiteringsgrunnlag(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentDebiteringsgrunnlag hentDebiteringsgrunnlag1, out SoapIntegration.BrukerInfo.Debiteringsgrunnlag Debiteringsgrunnlag) {
            SoapIntegration.BrukerInfo.hentDebiteringsgrunnlagRequest inValue = new SoapIntegration.BrukerInfo.hentDebiteringsgrunnlagRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.hentDebiteringsgrunnlag = hentDebiteringsgrunnlag1;
            SoapIntegration.BrukerInfo.hentDebiteringsgrunnlagResponse retVal = ((SoapIntegration.BrukerInfo.brukerinfoPortType)(this)).hentDebiteringsgrunnlag(inValue);
            Debiteringsgrunnlag = retVal.Debiteringsgrunnlag;
            return retVal.Transaksjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.BrukerInfo.hentPrislisteResponse SoapIntegration.BrukerInfo.brukerinfoPortType.hentPrisliste(SoapIntegration.BrukerInfo.hentPrislisteRequest request) {
            return base.Channel.hentPrisliste(request);
        }
        
        public SoapIntegration.BrukerInfo.Transaksjon hentPrisliste(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentPrisliste hentPrisliste1, out SoapIntegration.BrukerInfo.Prisliste Prisliste) {
            SoapIntegration.BrukerInfo.hentPrislisteRequest inValue = new SoapIntegration.BrukerInfo.hentPrislisteRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.hentPrisliste = hentPrisliste1;
            SoapIntegration.BrukerInfo.hentPrislisteResponse retVal = ((SoapIntegration.BrukerInfo.brukerinfoPortType)(this)).hentPrisliste(inValue);
            Prisliste = retVal.Prisliste;
            return retVal.Transaksjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.BrukerInfo.hentNyttPassordResponse SoapIntegration.BrukerInfo.brukerinfoPortType.hentNyttPassord(SoapIntegration.BrukerInfo.hentNyttPassordRequest request) {
            return base.Channel.hentNyttPassord(request);
        }
        
        public SoapIntegration.BrukerInfo.Transaksjon hentNyttPassord(SoapIntegration.BrukerInfo.Brukersesjon Brukersesjon, SoapIntegration.BrukerInfo.hentNyttPassord hentNyttPassord1, out SoapIntegration.BrukerInfo.NyttPassord NyttPassord) {
            SoapIntegration.BrukerInfo.hentNyttPassordRequest inValue = new SoapIntegration.BrukerInfo.hentNyttPassordRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.hentNyttPassord = hentNyttPassord1;
            SoapIntegration.BrukerInfo.hentNyttPassordResponse retVal = ((SoapIntegration.BrukerInfo.brukerinfoPortType)(this)).hentNyttPassord(inValue);
            NyttPassord = retVal.NyttPassord;
            return retVal.Transaksjon;
        }
    }
}
