//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapIntegration.Brukersesjon {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
    public partial class feil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string feilgruppekodeField;
        
        private string feilgruppetekstField;
        
        private string feilkodeField;
        
        private string feiltekstField;
        
        private string feilmeldingField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string feilgruppekode {
            get {
                return this.feilgruppekodeField;
            }
            set {
                this.feilgruppekodeField = value;
                this.RaisePropertyChanged("feilgruppekode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string feilgruppetekst {
            get {
                return this.feilgruppetekstField;
            }
            set {
                this.feilgruppetekstField = value;
                this.RaisePropertyChanged("feilgruppetekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string feilkode {
            get {
                return this.feilkodeField;
            }
            set {
                this.feilkodeField = value;
                this.RaisePropertyChanged("feilkode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string feiltekst {
            get {
                return this.feiltekstField;
            }
            set {
                this.feiltekstField = value;
                this.RaisePropertyChanged("feiltekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string feilmelding {
            get {
                return this.feilmeldingField;
            }
            set {
                this.feilmeldingField = value;
                this.RaisePropertyChanged("feilmelding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.wsdl", ConfigurationName="Brukersesjon.brukersesjonPortType")]
    public interface brukersesjonPortType {
        
        // CODEGEN: Generating message contract since the operation hentAutorisasjon is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.Brukersesjon.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.Brukersesjon.hentAutorisasjonResponse hentAutorisasjon(SoapIntegration.Brukersesjon.hentAutorisasjonRequest request);
        
        // CODEGEN: Generating message contract since the operation loggInn is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.Brukersesjon.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.Brukersesjon.loggInnResponse loggInn(SoapIntegration.Brukersesjon.loggInnRequest request);
        
        // CODEGEN: Generating message contract since the operation loggInnWeb is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.Brukersesjon.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.Brukersesjon.loggInnResponse loggInnWeb(SoapIntegration.Brukersesjon.loggInnWebRequest request);
        
        // CODEGEN: Generating message contract since the operation loggUt is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.Brukersesjon.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.Brukersesjon.loggUtResponse loggUt(SoapIntegration.Brukersesjon.loggUtRequest request);
        
        // CODEGEN: Generating message contract since the operation byttPassord is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapIntegration.Brukersesjon.feil), Action="", Name="feil", Namespace="http://ws.infotorg.no/xml/Feil/Feil.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapIntegration.Brukersesjon.byttPassordResponse byttPassord(SoapIntegration.Brukersesjon.byttPassordRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class Transaksjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referanseField;
        
        private bool visDetaljerField;
        
        private bool visDetaljerFieldSpecified;
        
        private bool visResponstidField;
        
        private bool visResponstidFieldSpecified;
        
        private bool visRaadataField;
        
        private bool visRaadataFieldSpecified;
        
        private string saksreferanseField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string referanse {
            get {
                return this.referanseField;
            }
            set {
                this.referanseField = value;
                this.RaisePropertyChanged("referanse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool visDetaljer {
            get {
                return this.visDetaljerField;
            }
            set {
                this.visDetaljerField = value;
                this.RaisePropertyChanged("visDetaljer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visDetaljerSpecified {
            get {
                return this.visDetaljerFieldSpecified;
            }
            set {
                this.visDetaljerFieldSpecified = value;
                this.RaisePropertyChanged("visDetaljerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool visResponstid {
            get {
                return this.visResponstidField;
            }
            set {
                this.visResponstidField = value;
                this.RaisePropertyChanged("visResponstid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visResponstidSpecified {
            get {
                return this.visResponstidFieldSpecified;
            }
            set {
                this.visResponstidFieldSpecified = value;
                this.RaisePropertyChanged("visResponstidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool visRaadata {
            get {
                return this.visRaadataField;
            }
            set {
                this.visRaadataField = value;
                this.RaisePropertyChanged("visRaadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visRaadataSpecified {
            get {
                return this.visRaadataFieldSpecified;
            }
            set {
                this.visRaadataFieldSpecified = value;
                this.RaisePropertyChanged("visRaadataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string saksreferanse {
            get {
                return this.saksreferanseField;
            }
            set {
                this.saksreferanseField = value;
                this.RaisePropertyChanged("saksreferanse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class hentAutorisasjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class Brukersesjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private distribusjonskanal distribusjonskanalField;
        
        private string systemnavnField;
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string delegertBrukernavnField;
        
        private string sesjonsidField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public distribusjonskanal distribusjonskanal {
            get {
                return this.distribusjonskanalField;
            }
            set {
                this.distribusjonskanalField = value;
                this.RaisePropertyChanged("distribusjonskanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string systemnavn {
            get {
                return this.systemnavnField;
            }
            set {
                this.systemnavnField = value;
                this.RaisePropertyChanged("systemnavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brukernavn", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("passord", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string delegertBrukernavn {
            get {
                return this.delegertBrukernavnField;
            }
            set {
                this.delegertBrukernavnField = value;
                this.RaisePropertyChanged("delegertBrukernavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sesjonsid {
            get {
                return this.sesjonsidField;
            }
            set {
                this.sesjonsidField = value;
                this.RaisePropertyChanged("sesjonsid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public enum distribusjonskanal {
        
        /// <remarks/>
        PTP,
        
        /// <remarks/>
        GUI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":brukernavn")]
        brukernavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":passord")]
        passord,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class Transaksjonsinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransaksjonsinfoSammendrag sammendragField;
        
        private TransaksjonsinfoTransaksjon[] detaljerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TransaksjonsinfoSammendrag sammendrag {
            get {
                return this.sammendragField;
            }
            set {
                this.sammendragField = value;
                this.RaisePropertyChanged("sammendrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaksjon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransaksjonsinfoTransaksjon[] detaljer {
            get {
                return this.detaljerField;
            }
            set {
                this.detaljerField = value;
                this.RaisePropertyChanged("detaljer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class TransaksjonsinfoSammendrag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string datakildeField;
        
        private string tjenesteField;
        
        private string produktField;
        
        private string referanseField;
        
        private string antallTransaksjonerField;
        
        private debitering debiteringField;
        
        private responstid responstidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string datakilde {
            get {
                return this.datakildeField;
            }
            set {
                this.datakildeField = value;
                this.RaisePropertyChanged("datakilde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tjeneste {
            get {
                return this.tjenesteField;
            }
            set {
                this.tjenesteField = value;
                this.RaisePropertyChanged("tjeneste");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string produkt {
            get {
                return this.produktField;
            }
            set {
                this.produktField = value;
                this.RaisePropertyChanged("produkt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string referanse {
            get {
                return this.referanseField;
            }
            set {
                this.referanseField = value;
                this.RaisePropertyChanged("referanse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public string antallTransaksjoner {
            get {
                return this.antallTransaksjonerField;
            }
            set {
                this.antallTransaksjonerField = value;
                this.RaisePropertyChanged("antallTransaksjoner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public debitering debitering {
            get {
                return this.debiteringField;
            }
            set {
                this.debiteringField = value;
                this.RaisePropertyChanged("debitering");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public responstid responstid {
            get {
                return this.responstidField;
            }
            set {
                this.responstidField = value;
                this.RaisePropertyChanged("responstid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class debitering : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string debitertField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string debitert {
            get {
                return this.debitertField;
            }
            set {
                this.debitertField = value;
                this.RaisePropertyChanged("debitert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class responstid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string totalField;
        
        private string internField;
        
        private string backOfficeField;
        
        private string datakildeField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="duration", Order=0)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="duration", Order=1)]
        public string intern {
            get {
                return this.internField;
            }
            set {
                this.internField = value;
                this.RaisePropertyChanged("intern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="duration", Order=2)]
        public string backOffice {
            get {
                return this.backOfficeField;
            }
            set {
                this.backOfficeField = value;
                this.RaisePropertyChanged("backOffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="duration", Order=3)]
        public string datakilde {
            get {
                return this.datakildeField;
            }
            set {
                this.datakildeField = value;
                this.RaisePropertyChanged("datakilde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class TransaksjonsinfoTransaksjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string datakildeField;
        
        private string tjenesteField;
        
        private string produktField;
        
        private debitering debiteringField;
        
        private responstid responstidField;
        
        private raadata raadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string datakilde {
            get {
                return this.datakildeField;
            }
            set {
                this.datakildeField = value;
                this.RaisePropertyChanged("datakilde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tjeneste {
            get {
                return this.tjenesteField;
            }
            set {
                this.tjenesteField = value;
                this.RaisePropertyChanged("tjeneste");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string produkt {
            get {
                return this.produktField;
            }
            set {
                this.produktField = value;
                this.RaisePropertyChanged("produkt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public debitering debitering {
            get {
                return this.debiteringField;
            }
            set {
                this.debiteringField = value;
                this.RaisePropertyChanged("debitering");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public responstid responstid {
            get {
                return this.responstidField;
            }
            set {
                this.responstidField = value;
                this.RaisePropertyChanged("responstid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public raadata raadata {
            get {
                return this.raadataField;
            }
            set {
                this.raadataField = value;
                this.RaisePropertyChanged("raadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
    public partial class raadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string spoerringField;
        
        private string svarField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string spoerring {
            get {
                return this.spoerringField;
            }
            set {
                this.spoerringField = value;
                this.RaisePropertyChanged("spoerring");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string svar {
            get {
                return this.svarField;
            }
            set {
                this.svarField = value;
                this.RaisePropertyChanged("svar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class Autorisasjon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool byttPassordField;
        
        private string sesjonstimeoutField;
        
        private System.Nullable<System.DateTime> passordutloepField;
        
        private System.Nullable<System.DateTime> brukerutloepField;
        
        private bool ulestPostField;
        
        private bool ulestMeldingField;
        
        private AutorisasjonTjeneste[] tjenesterField;
        
        private string autosysSelskapField;
        
        private bool oppdaterKontaktinfoField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool byttPassord {
            get {
                return this.byttPassordField;
            }
            set {
                this.byttPassordField = value;
                this.RaisePropertyChanged("byttPassord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="duration", IsNullable=true, Order=1)]
        public string sesjonstimeout {
            get {
                return this.sesjonstimeoutField;
            }
            set {
                this.sesjonstimeoutField = value;
                this.RaisePropertyChanged("sesjonstimeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> passordutloep {
            get {
                return this.passordutloepField;
            }
            set {
                this.passordutloepField = value;
                this.RaisePropertyChanged("passordutloep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> brukerutloep {
            get {
                return this.brukerutloepField;
            }
            set {
                this.brukerutloepField = value;
                this.RaisePropertyChanged("brukerutloep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool ulestPost {
            get {
                return this.ulestPostField;
            }
            set {
                this.ulestPostField = value;
                this.RaisePropertyChanged("ulestPost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool ulestMelding {
            get {
                return this.ulestMeldingField;
            }
            set {
                this.ulestMeldingField = value;
                this.RaisePropertyChanged("ulestMelding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tjeneste", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AutorisasjonTjeneste[] tjenester {
            get {
                return this.tjenesterField;
            }
            set {
                this.tjenesterField = value;
                this.RaisePropertyChanged("tjenester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string autosysSelskap {
            get {
                return this.autosysSelskapField;
            }
            set {
                this.autosysSelskapField = value;
                this.RaisePropertyChanged("autosysSelskap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool oppdaterKontaktinfo {
            get {
                return this.oppdaterKontaktinfoField;
            }
            set {
                this.oppdaterKontaktinfoField = value;
                this.RaisePropertyChanged("oppdaterKontaktinfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=9)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class AutorisasjonTjeneste : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string navnField;
        
        private string datakildeField;
        
        private AutorisasjonTjenesteProdukt[] produkterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string datakilde {
            get {
                return this.datakildeField;
            }
            set {
                this.datakildeField = value;
                this.RaisePropertyChanged("datakilde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("produkt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AutorisasjonTjenesteProdukt[] produkter {
            get {
                return this.produkterField;
            }
            set {
                this.produkterField = value;
                this.RaisePropertyChanged("produkter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class AutorisasjonTjenesteProdukt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string navnField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
                this.RaisePropertyChanged("navn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentAutorisasjonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.hentAutorisasjon hentAutorisasjon;
        
        public hentAutorisasjonRequest() {
        }
        
        public hentAutorisasjonRequest(SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.hentAutorisasjon hentAutorisasjon) {
            this.Transaksjon = Transaksjon;
            this.hentAutorisasjon = hentAutorisasjon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hentAutorisasjonResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.Autorisasjon Autorisasjon;
        
        public hentAutorisasjonResponse() {
        }
        
        public hentAutorisasjonResponse(SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo, SoapIntegration.Brukersesjon.Autorisasjon Autorisasjon) {
            this.Brukersesjon = Brukersesjon;
            this.Transaksjonsinfo = Transaksjonsinfo;
            this.Autorisasjon = Autorisasjon;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class loggInn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private distribusjonskanal distribusjonskanalField;
        
        private string systemnavnField;
        
        private string[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        private string delegertBrukernavnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public distribusjonskanal distribusjonskanal {
            get {
                return this.distribusjonskanalField;
            }
            set {
                this.distribusjonskanalField = value;
                this.RaisePropertyChanged("distribusjonskanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string systemnavn {
            get {
                return this.systemnavnField;
            }
            set {
                this.systemnavnField = value;
                this.RaisePropertyChanged("systemnavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brukernavn", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("passord", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string delegertBrukernavn {
            get {
                return this.delegertBrukernavnField;
            }
            set {
                this.delegertBrukernavnField = value;
                this.RaisePropertyChanged("delegertBrukernavn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":brukernavn")]
        brukernavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":passord")]
        passord,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggInnRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.loggInn loggInn;
        
        public loggInnRequest() {
        }
        
        public loggInnRequest(SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.loggInn loggInn) {
            this.Transaksjon = Transaksjon;
            this.loggInn = loggInn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggInnResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.Autorisasjon Autorisasjon;
        
        public loggInnResponse() {
        }
        
        public loggInnResponse(SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo, SoapIntegration.Brukersesjon.Autorisasjon Autorisasjon) {
            this.Brukersesjon = Brukersesjon;
            this.Transaksjonsinfo = Transaksjonsinfo;
            this.Autorisasjon = Autorisasjon;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class loggInnWeb : object, System.ComponentModel.INotifyPropertyChanged {
        
        private distribusjonskanal distribusjonskanalField;
        
        private string systemnavnField;
        
        private string[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        private string delegertBrukernavnField;
        
        private string autorisasjonsnoekkelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public distribusjonskanal distribusjonskanal {
            get {
                return this.distribusjonskanalField;
            }
            set {
                this.distribusjonskanalField = value;
                this.RaisePropertyChanged("distribusjonskanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string systemnavn {
            get {
                return this.systemnavnField;
            }
            set {
                this.systemnavnField = value;
                this.RaisePropertyChanged("systemnavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brukernavn", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("passord", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string delegertBrukernavn {
            get {
                return this.delegertBrukernavnField;
            }
            set {
                this.delegertBrukernavnField = value;
                this.RaisePropertyChanged("delegertBrukernavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string autorisasjonsnoekkel {
            get {
                return this.autorisasjonsnoekkelField;
            }
            set {
                this.autorisasjonsnoekkelField = value;
                this.RaisePropertyChanged("autorisasjonsnoekkel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":brukernavn")]
        brukernavn,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":passord")]
        passord,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggInnWebRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.loggInnWeb loggInnWeb;
        
        public loggInnWebRequest() {
        }
        
        public loggInnWebRequest(SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.loggInnWeb loggInnWeb) {
            this.Transaksjon = Transaksjon;
            this.loggInnWeb = loggInnWeb;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class loggUt : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class OK : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggUtRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.loggUt loggUt;
        
        public loggUtRequest() {
        }
        
        public loggUtRequest(SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.loggUt loggUt) {
            this.Brukersesjon = Brukersesjon;
            this.Transaksjon = Transaksjon;
            this.loggUt = loggUt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggUtResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.OK OK;
        
        public loggUtResponse() {
        }
        
        public loggUtResponse(SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo, SoapIntegration.Brukersesjon.OK OK) {
            this.Brukersesjon = Brukersesjon;
            this.Transaksjonsinfo = Transaksjonsinfo;
            this.OK = OK;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
    public partial class byttPassord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brukernavnField;
        
        private string passordField;
        
        private string nyttPassordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string brukernavn {
            get {
                return this.brukernavnField;
            }
            set {
                this.brukernavnField = value;
                this.RaisePropertyChanged("brukernavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string passord {
            get {
                return this.passordField;
            }
            set {
                this.passordField = value;
                this.RaisePropertyChanged("passord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nyttPassord {
            get {
                return this.nyttPassordField;
            }
            set {
                this.nyttPassordField = value;
                this.RaisePropertyChanged("nyttPassord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class byttPassordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjon Transaksjon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.byttPassord byttPassord;
        
        public byttPassordRequest() {
        }
        
        public byttPassordRequest(SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.byttPassord byttPassord) {
            this.Brukersesjon = Brukersesjon;
            this.Transaksjon = Transaksjon;
            this.byttPassord = byttPassord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class byttPassordResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd")]
        public SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Transaksjon/2006-07-07/Transaksjon.xsd")]
        public SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.infotorg.no/xml/Admin/Brukersesjon/2006-07-07/Brukersesjon.xsd", Order=0)]
        public SoapIntegration.Brukersesjon.OK OK;
        
        public byttPassordResponse() {
        }
        
        public byttPassordResponse(SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo, SoapIntegration.Brukersesjon.OK OK) {
            this.Brukersesjon = Brukersesjon;
            this.Transaksjonsinfo = Transaksjonsinfo;
            this.OK = OK;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface brukersesjonPortTypeChannel : SoapIntegration.Brukersesjon.brukersesjonPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class brukersesjonPortTypeClient : System.ServiceModel.ClientBase<SoapIntegration.Brukersesjon.brukersesjonPortType>, SoapIntegration.Brukersesjon.brukersesjonPortType {
        
        public brukersesjonPortTypeClient() {
        }
        
        public brukersesjonPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public brukersesjonPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public brukersesjonPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public brukersesjonPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.Brukersesjon.hentAutorisasjonResponse SoapIntegration.Brukersesjon.brukersesjonPortType.hentAutorisasjon(SoapIntegration.Brukersesjon.hentAutorisasjonRequest request) {
            return base.Channel.hentAutorisasjon(request);
        }
        
        public SoapIntegration.Brukersesjon.Brukersesjon hentAutorisasjon(SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.hentAutorisasjon hentAutorisasjon1, out SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo, out SoapIntegration.Brukersesjon.Autorisasjon Autorisasjon) {
            SoapIntegration.Brukersesjon.hentAutorisasjonRequest inValue = new SoapIntegration.Brukersesjon.hentAutorisasjonRequest();
            inValue.Transaksjon = Transaksjon;
            inValue.hentAutorisasjon = hentAutorisasjon1;
            SoapIntegration.Brukersesjon.hentAutorisasjonResponse retVal = ((SoapIntegration.Brukersesjon.brukersesjonPortType)(this)).hentAutorisasjon(inValue);
            Transaksjonsinfo = retVal.Transaksjonsinfo;
            Autorisasjon = retVal.Autorisasjon;
            return retVal.Brukersesjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.Brukersesjon.loggInnResponse SoapIntegration.Brukersesjon.brukersesjonPortType.loggInn(SoapIntegration.Brukersesjon.loggInnRequest request) {
            return base.Channel.loggInn(request);
        }
        
        public SoapIntegration.Brukersesjon.Brukersesjon loggInn(SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.loggInn loggInn1, out SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo, out SoapIntegration.Brukersesjon.Autorisasjon Autorisasjon) {
            SoapIntegration.Brukersesjon.loggInnRequest inValue = new SoapIntegration.Brukersesjon.loggInnRequest();
            inValue.Transaksjon = Transaksjon;
            inValue.loggInn = loggInn1;
            SoapIntegration.Brukersesjon.loggInnResponse retVal = ((SoapIntegration.Brukersesjon.brukersesjonPortType)(this)).loggInn(inValue);
            Transaksjonsinfo = retVal.Transaksjonsinfo;
            Autorisasjon = retVal.Autorisasjon;
            return retVal.Brukersesjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.Brukersesjon.loggInnResponse SoapIntegration.Brukersesjon.brukersesjonPortType.loggInnWeb(SoapIntegration.Brukersesjon.loggInnWebRequest request) {
            return base.Channel.loggInnWeb(request);
        }
        
        public SoapIntegration.Brukersesjon.Brukersesjon loggInnWeb(SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.loggInnWeb loggInnWeb1, out SoapIntegration.Brukersesjon.Transaksjonsinfo Transaksjonsinfo, out SoapIntegration.Brukersesjon.Autorisasjon Autorisasjon) {
            SoapIntegration.Brukersesjon.loggInnWebRequest inValue = new SoapIntegration.Brukersesjon.loggInnWebRequest();
            inValue.Transaksjon = Transaksjon;
            inValue.loggInnWeb = loggInnWeb1;
            SoapIntegration.Brukersesjon.loggInnResponse retVal = ((SoapIntegration.Brukersesjon.brukersesjonPortType)(this)).loggInnWeb(inValue);
            Transaksjonsinfo = retVal.Transaksjonsinfo;
            Autorisasjon = retVal.Autorisasjon;
            return retVal.Brukersesjon;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.Brukersesjon.loggUtResponse SoapIntegration.Brukersesjon.brukersesjonPortType.loggUt(SoapIntegration.Brukersesjon.loggUtRequest request) {
            return base.Channel.loggUt(request);
        }
        
        public SoapIntegration.Brukersesjon.Transaksjonsinfo loggUt(ref SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.loggUt loggUt1, out SoapIntegration.Brukersesjon.OK OK) {
            SoapIntegration.Brukersesjon.loggUtRequest inValue = new SoapIntegration.Brukersesjon.loggUtRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.Transaksjon = Transaksjon;
            inValue.loggUt = loggUt1;
            SoapIntegration.Brukersesjon.loggUtResponse retVal = ((SoapIntegration.Brukersesjon.brukersesjonPortType)(this)).loggUt(inValue);
            Brukersesjon = retVal.Brukersesjon;
            OK = retVal.OK;
            return retVal.Transaksjonsinfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapIntegration.Brukersesjon.byttPassordResponse SoapIntegration.Brukersesjon.brukersesjonPortType.byttPassord(SoapIntegration.Brukersesjon.byttPassordRequest request) {
            return base.Channel.byttPassord(request);
        }
        
        public SoapIntegration.Brukersesjon.Transaksjonsinfo byttPassord(ref SoapIntegration.Brukersesjon.Brukersesjon Brukersesjon, SoapIntegration.Brukersesjon.Transaksjon Transaksjon, SoapIntegration.Brukersesjon.byttPassord byttPassord1, out SoapIntegration.Brukersesjon.OK OK) {
            SoapIntegration.Brukersesjon.byttPassordRequest inValue = new SoapIntegration.Brukersesjon.byttPassordRequest();
            inValue.Brukersesjon = Brukersesjon;
            inValue.Transaksjon = Transaksjon;
            inValue.byttPassord = byttPassord1;
            SoapIntegration.Brukersesjon.byttPassordResponse retVal = ((SoapIntegration.Brukersesjon.brukersesjonPortType)(this)).byttPassord(inValue);
            Brukersesjon = retVal.Brukersesjon;
            OK = retVal.OK;
            return retVal.Transaksjonsinfo;
        }
    }
}
